[bot]

    [bot.general]
    codename = "Employee of the Month"

    [bot.discord]
    appid = "" # replace with unquoted integer
    token = ""

    [bot.logging]
    enabled = true
    level = "info"

